on: push
jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create config.json
        run: |
          echo '{' > config.json
          echo '  "token": "${{ secrets.TOKEN }}",' >> config.json
          echo '  "facts": "${{ secrets.FACTS }}"' >> config.json
          echo '}' >> config.json

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: node .
