on: push
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create config.json
        run: |
          echo '{' > config.json
          echo '  "token": "${{ secrets.TOKEN }}",' >> config.json
          echo '  "facts": "${{ secrets.FACTS }}"' >> config.json
          echo '}' >> config.json

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: timeout 20s node .

      - name: Kill Bot
        run: pkill -f "node ."
